poll_interval: 5m          # how often to check for cert changes
tls_dial_timeout: 10s      # timeout for connecting to IPMI HTTPS
saa_binary: /opt/saa/saa   # path to SAA executable

servers:
  - name: smx01
    ipmi_host: 192.168.1.11
    cert_path: /certs/smx01/tls.crt
    key_path: /certs/smx01/tls.key
    credentials:
      username_file: /credentials/username
      password_file: /credentials/password
  - name: smx02
    ipmi_host: 192.168.1.12
    cert_path: /certs/smx02/tls.crt
    key_path: /certs/smx02/tls.key
    credentials:
      username_file: /credentials/username
      password_file: /credentials/password
  - name: smx03
    ipmi_host: 192.168.1.13
    cert_path: /certs/smx03/tls.crt
    key_path: /certs/smx03/tls.key
    credentials:
      username_file: /credentials/username
      password_file: /credentials/password
  - name: smx04
    ipmi_host: 192.168.1.14
    cert_path: /certs/smx04/tls.crt
    key_path: /certs/smx04/tls.key
    credentials:
      username_file: /credentials/username
      password_file: /credentials/password