apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipmi-cert-pusher
  namespace: ipmi-updater
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ipmi-cert-pusher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ipmi-cert-pusher
    spec:
      containers:
      - image: ghcr.io/matt-e/ipmi-cert-pusher:0.1
        imagePullPolicy: IfNotPresent
        name: ipmi-cert-pusher
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ipmi-cert-pusher
          name: config
          readOnly: true
        - mountPath: /certs/smx01
          name: smx01-tls
          readOnly: true
        - mountPath: /certs/smx02
          name: smx02-tls
          readOnly: true
        - mountPath: /certs/smx03
          name: smx03-tls
          readOnly: true
        - mountPath: /certs/smx04
          name: smx04-tls
          readOnly: true
        - mountPath: /credentials
          name: credentials
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: config
        name: config
      - name: smx01-tls
        secret:
          secretName: smx01-ipmi-eddey-net-tls
      - name: smx02-tls
        secret:
          secretName: smx02-ipmi-eddey-net-tls
      - name: smx03-tls
        secret:
          secretName: smx03-ipmi-eddey-net-tls
      - name: smx04-tls
        secret:
          secretName: smx04-ipmi-eddey-net-tls
      - name: credentials
        secret:
          secretName: ipmi-credentials