apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: config
  files:
  - config.yaml

resources:
  - namespace.yaml
  - deployments.apps.yaml
  - certificates.yaml
  - services.yaml
  - servicemonitor.yaml
namespace: ipmi-updater
